force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Status_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Update_Date__c</fullName>
    <label>Status Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Visiting People</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Visited Locations</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CTLocationTriggerHandler.cls
/**
 * CTLocationTriggerHandler
 * Handler class for Location__c Trigger
 * @author Manish
 */
public with sharing class CTLocationTriggerHandler {
    // Before insert operation for Location__c object
    // make sure the health status is green
    public static void beforeInsert(List<Location__c> newRecords) {
        for (Location__c location : newRecords) {
            // update location status to Green
            location.Status__c = 'Green';
        }
    }

    // Before update operation for Location__c object
    public static void beforeUpdate(List<Location__c> locations, Map<Id, Location__c> oldValues) {
        for (Location__c location : locations) {
            // check if the status changed in this transaction
            // also update Status_Update_Date__c
            if (location.Status__c != oldValues.get(location.Id).Status__c) {
                location.Status_Update_Date__c = Date.today();
            }
        }
    }

    // After update operation for Location__c object
    public static void afterUpdate(List<Location__c> locations, Map<Id, Location__c> oldValues) {
        // list of location with changed status
        Set<Id> statusChange = new Set<Id>();
        for (Location__c location : locations) {
            // check if the status changed in this transaction
            // also update Status_Update_Date__c
            if (location.Status__c == 'Red' && location.Status__c != oldValues.get(location.Id).Status__c) {
                statusChange.add(location.Id);
            }
        }
        // get location traces
        List<Location_Tracing__c> locationTraces = CTLocationTracingController.getLocationsByLocationIds(statusChange);
        // get people list
        List<Person__c> peopleToUpdate = new List<Person__c>();
        Set<Id> personIds = new Set<Id>();
        for (Location_Tracing__c trace : locationTraces) {
            personIds.add(trace.Person__c);
        }

        for (Id personId : personIds) {
            peopleToUpdate.add(new Person__c(Id = personId, Health_Status__c = 'Yellow'));
        }

        update peopleToUpdate;
    }
}