force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Visiting People</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Visited Locations</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <label>Visit Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/People_Tracing__c.object-meta.xml
<CustomObject>
    <label>People Tracing</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People_Tracing__c/fields/Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Contact_Date__c</fullName>
    <label>Contact Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cohabitant</fullName>
            </value>
            <value>
                <fullName>Neighbour</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_1__c.field-meta.xml
<CustomField>
    <fullName>Person_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person 1</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Primary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_2__c.field-meta.xml
<CustomField>
    <fullName>Person_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 2</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Secondary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CTTestFactory.cls
public with sharing class CTTestFactory {
    public static List<Person__c> getPeople(List<String> names) {
        List<Person__c> testRecords = new List<Person__c>();
        Integer i = 0;
        for (String name : names) {
            testRecords.add(new Person__c(Name = name, Mobile__c = '99889988' + i));
            i++;
        }
        insert testRecords;
        return testRecords;
    }

    public static People_Tracing__c getPeopleTrace(Id person1, Id person2, String type) {
        People_Tracing__c testRecord = new People_Tracing__c(Person_1__c = person1, Person_2__c = person2, Contact_Type__c = type, Contact_Date__c = Date.today());
        insert testRecord;
        return testRecord;
    }

    public static List<Location__c> getLocations(List<String> names) {
        List<Location__c> testRecords = new List<Location__c>();
        Integer i = 0;
        for (String name : names) {
            testRecords.add(new Location__c(Name = name, Pincode__c = '1011' + i, Address__c = '5th Avenue bld #' + i));
        }
        insert testRecords;
        return testRecords;
    }

    public static Location_Tracing__c getLocationTrace(Id person, Id location) {
        Location_Tracing__c testRecord = new Location_Tracing__c(Person__c = person, Location__c = location, Visit_Date__c = Date.today());
        insert testRecord;
        return testRecord;
    }

    public static List<Person__c> getPeople(Integer numberOfRecords) {
        List<Person__c> testRecords = new List<Person__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            testRecords.add(new Person__c(Name = 'Test' + i, Mobile__c = '99889988' + i));
        }
        insert testRecords;
        return testRecords;
    }

    public static List<Location__c> getLocations(Integer numberOfRecords) {
        List<Location__c> testRecords = new List<Location__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            testRecords.add(new Location__c(Name = 'Test' + i, Pincode__c = '1011' + i, Address__c = '5th Avenue bld #' + i));
        }
        insert testRecords;
        return testRecords;
    }
}