force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Red_Score__c.field-meta.xml
<CustomField>
    <fullName>Red_Score__c</fullName>
    <label>Red Score</label>
    <summaryForeignKey>Location_Tracing__c.Location__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Visiting People</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Visited Locations</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CTLocationController.cls
/**
 * CTLocationController
 * Main controller of Location__c object
 * @author Manish
 */
public with sharing class CTLocationController {
    /**
     * Update redScore of locations
     * Red score is updated based on the number of
     * red health status person visited the location
     * @param locationIds
     * @return locations
     */
    public static List<Location__c> updateRedScore(Set<Id> locationIds) {
        // query location tracing records for all locations
        // retrive person health status as well
        List<Location_Tracing__c> locationTraces = [
            SELECT Id, Person__r.Health_Status__c, Location__c
            FROM Location_Tracing__c
            WHERE Location__c IN :locationIds
        ];
        if (locationIds != null && locationIds.size() > 0) {
            // create a map of location id and count of red score
            Map<Id, Integer> redScoreMap = new Map<Id, Integer>();

            String key;
            Integer count;
            // iterate over location traces
            for (Location_Tracing__c locationTrace : locationTraces) {
                // get current location id
                key = locationTrace.Location__c;
                // if redScoreMap does not have this key
                // then add this location (as key) with zero count
                if (!redScoreMap.containsKey(key)) {
                    redScoreMap.put(key, 0);
                }

                // get current red score count
                count = redScoreMap.get(key);
                // increment red score by 1
                redScoreMap.put(key, ++count);
            }

            // Map is ready, now create instance of all location records from ids
            List<Location__c> locations = new List<Location__c>();
            for (Id locationId : redScoreMap.keySet()) {
                // get red score
                Integer redScore = redScoreMap.get(locationId);
                Location__c loc = new Location__c(
                    Id = locationId,
                    Red_Score__c = redScore,
                    Status__c = getStatus(redScore)
                );
                locations.add(loc);
            }

            // Update these location records
            if (locations != null && locations.size() > 0) {
                update locations;
                return locations;
            }
            return null;
        }
        return null;
    }

    /**
     * get status of location based on red score
     * Red - If there are more than 10 people (Red Score) who visited the location in last 10 days are in red status
     * Orange - If there are more than 5 people (Red Score) who visited the location in last 10 days are in red status
     * Yellow - If there are more than 1 people (Red Score) who visited the location in last 10 days are in red status
     * Green - Safe
     * @param redScore
     * @return string status
     */
    public static String getStatus(Integer redScore) {
        if (redScore == 0) {
            return 'Green';
        } else if (redScore <= 5) {
            return 'Yellow';
        } else if (redScore <= 10) {
            return 'Orange';
        } else {
            return 'Red';
        }
    }
}