force-app/main/default/objects/People_Tracing__c/People_Tracing__c.object-meta.xml
<CustomObject>
    <label>People Tracing</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People_Tracing__c/fields/Person_1__c.field-meta.xml
<CustomField>
    <fullName>Person_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person 1</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Primary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_2__c.field-meta.xml
<CustomField>
    <fullName>Person_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 2</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Secondary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CTPeopleTracingController.cls
/**
 * CTPeopleTracingController
 * Main controller of People_Tracing__c  object
 * @author Manish
 */
public with sharing class CTPeopleTracingController {
    /**
     * Check duplicate People Tracing records
     * for multiple combinations
     * @param token1 token of first user
     * @param token2 token of 2nd user
     * @return boolean
     */
    public static boolean isDuplicate(String token1, String token2) {
        List<People_Tracing__c> people = [
            SELECT Id
            FROM People_Tracing__c
            WHERE
                (Person_1__r.Token__c = :token1
                AND Person_2__r.Token__c = :token2)
                OR (Person_1__r.Token__c = :token2
                AND Person_2__r.Token__c = :token1)
        ];
        return people != null && people.size() > 0 ? true : false;
    }
}