force-app/main/default/objects/People_Tracing__c/People_Tracing__c.object-meta.xml
<CustomObject>
    <label>People Tracing</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People_Tracing__c/fields/Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Contact_Date__c</fullName>
    <label>Contact Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_1__c.field-meta.xml
<CustomField>
    <fullName>Person_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person 1</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Primary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_2__c.field-meta.xml
<CustomField>
    <fullName>Person_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 2</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Secondary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CTUserTabController.cls
/**
 * CTUserTabController
 * Main controller of CTUserTab Aura Component
 * @author Manish
 */
public with sharing class CTUserTabController {
    @AuraEnabled
    public static UserInformation getUserDetails(String recordId) {
        UserInformation info = new UserInformation();

        Person__c person = CTPersonController.getPersonById(recordId);
        if (person != null) {
            info.name = person.Name;
            info.token = person.Token__c;
            info.statusUpdateOn = person.Status_Update_Date__c;
            info.phone = person.Mobile__c;
            info.status = person.Health_Status__c;
        }

        List<People_Tracing__c> traces = CTPeopleTracingController.getTraces(recordId);
        if (traces != null && traces.size() > 0) {
            List<CloseContact> contacts = new List<CloseContact>();
            Set<String> uniqueIds = new Set<String>();
            uniqueIds.add(recordId);

            for (People_Tracing__c trace : traces) {
                if (!uniqueIds.contains(trace.Person_1__c)) {
                    CloseContact cc = new CloseContact();
                    cc.contactDate = trace.Contact_Date__c;
                    cc.status = trace.Person_1__r.Health_Status__c;
                    cc.token = trace.Person_1__r.Token__c;
                    cc.id = trace.Person_1__c;
                    contacts.add(cc);
                    uniqueIds.add(trace.Person_1__c);
                }
                if (!uniqueIds.contains(trace.Person_2__c)) {
                    CloseContact cc = new CloseContact();
                    cc.contactDate = trace.Contact_Date__c;
                    cc.status = trace.Person_2__r.Health_Status__c;
                    cc.token = trace.Person_2__r.Token__c;
                    cc.id = trace.Person_2__c;
                    contacts.add(cc);
                    uniqueIds.add(trace.Person_2__c);
                }
            }
            info.contacts = contacts;
            info.contactsCount = contacts.size();
        }
        return info;
    }

    public class UserInformation {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String token;
        @AuraEnabled
        public Date statusUpdateOn;
        @AuraEnabled
        public String phone;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public Integer contactsCount = 0;
        @AuraEnabled
        public List<CloseContact> contacts;
    }

    public class CloseContact {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String token;
        @AuraEnabled
        public Date contactDate;
        @AuraEnabled
        public String status;
    }
}