force-app/main/default/objects/People_Tracing__c/People_Tracing__c.object-meta.xml
<CustomObject>
    <label>People Tracing</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People_Tracing__c/fields/Person_1__c.field-meta.xml
<CustomField>
    <fullName>Person_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person 1</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Primary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People_Tracing__c/fields/Person_2__c.field-meta.xml
<CustomField>
    <fullName>Person_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 2</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Secondary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CTPeopleTracingTriggerHandler.cls
/**
 * CTPeopleTracingTriggerHandler
 * Handler class for People_Tracing__c Trigger
 * @author Manish
 */
public with sharing class CTPeopleTracingTriggerHandler {
    // Before insert operation for People_Tracing__c object
    // check duplicates and make decision
    public static void beforeInsert(List<People_Tracing__c> newRecords) {
        // unique records ids
        Set<Id> recordIds = new Set<Id>();
        for (People_Tracing__c trace : newRecords) {
            recordIds.add(trace.Person_1__c);
            recordIds.add(trace.Person_2__c);
        }

        // Check for duplicates
        List<People_Tracing__c> duplicates = CTPeopleTracingController.checkDuplicates(newRecords, recordIds);

        // Add error on duplicates
        for (People_Tracing__c trace : duplicates) {
            trace.addError('Duplicate record found. Person 1:' + trace.Person_1__c + ' Person 2:' + trace.Person_2__c);
        }
    }
}