force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <label>Visit Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CTLocationTracingDataCleanupBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-14-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   06-14-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class CTLocationTracingDataCleanupBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id FROM Location_Tracing__c WHERE Visit_Date__c < LAST_N_DAYS : 30');
     }
     
     public void execute(
                  Database.BatchableContext BC, 
                  List<Location_Tracing__c> scope){
        delete scope;
     }
   
    public void finish(Database.BatchableContext BC){

    }
}